### ISSUE TITLE
Milestone: Send a script to a Rust programmer, explain constraints and support running a program they come up with within these constraints.

### ISSUE THREAD

**Issue by cognivore** [lurk-lab/Wasm.lean#67]
# Why?

If wasm.lean is to be a backbone of some product, then the experiment @cognivore ran with writing a viable non-trivial program in Rust, compiling to WASM, exporting to WAST and running with Wasm.lean should be reproducible for any rust programmer and any reasonably small Rust program they write without floats and without non-determinism.

# What?

 - [ ] Instructions for the constraints to consider while writing this rust program (no floats, no real entropy, no libraries aside from stdlib, etc).
 - [ ] Instructions for how to prepare rust program.
 - [ ] A binary or even shell script that bundles everything needed and runs it on a default architecture ([see a private discussion in Zulip about what should default architecture be](https://zulip.yatima.io/#narrow/stream/22-inc/topic/Default.20arch/near/62814)). The user can write their program and run it on lurk e2e with this binary bundle.
